version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs", "browser", "jquery"]
module_system = "es-modules"
dependency_files = [
  "package.json",
  "bower.json"
]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
mode = "basic"

[excludes]
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  ".cache/",
  "public/"
]

[test-patterns]
paths = [
  "**/*.test.js",
  "**/*.spec.js"
]

[metrics]
enabled = true
