version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
runtime_version = "latest"
environment = ["nodejs", "browser"]
style_guide = "standard"
module_system = "es-modules"
dialect = "typescript"  # Agregado para soporte TypeScript

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
mode = "basic"

[[analyzers]]
name = "eslint"
enabled = true

[analyzers.meta]
plugin_paths = [".eslintrc.js"]

# Ignorar carpetas innecesarias
[excludes]
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  ".cache/",
  "public/"
]

[test-patterns]
paths = [
  "**/*.test.js",
  "**/*.spec.js"
]

# Configuración de métricas de código
[metrics]
enabled = true
